// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: education.sql

package model

import (
	"context"
)

const insertEducation = `-- name: InsertEducation :exec
INSERT INTO educations
(person_id, organization_id, degree_id, study_field_id, "description", start_year, start_month, end_year, end_month)
VALUES
(?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEducationParams struct {
	PersonID       int64   `db:"person_id"`
	OrganizationID int64   `db:"organization_id"`
	DegreeID       int64   `db:"degree_id"`
	StudyFieldID   int64   `db:"study_field_id"`
	Description    *string `db:"description"`
	StartYear      *int64  `db:"start_year"`
	StartMonth     *string `db:"start_month"`
	EndYear        *int64  `db:"end_year"`
	EndMonth       *string `db:"end_month"`
}

func (q *Queries) InsertEducation(ctx context.Context, arg InsertEducationParams) error {
	_, err := q.db.ExecContext(ctx, insertEducation,
		arg.PersonID,
		arg.OrganizationID,
		arg.DegreeID,
		arg.StudyFieldID,
		arg.Description,
		arg.StartYear,
		arg.StartMonth,
		arg.EndYear,
		arg.EndMonth,
	)
	return err
}
