// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: experience.sql

package model

import (
	"context"
)

const insertExperience = `-- name: InsertExperience :exec
INSERT INTO experiences
(person_id, organization_id, title, location_raw, "description", start_year, start_month, is_current, end_year, end_month, skills_url)
VALUES
(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertExperienceParams struct {
	PersonID       int64   `db:"person_id"`
	OrganizationID int64   `db:"organization_id"`
	Title          string  `db:"title"`
	LocationRaw    *string `db:"location_raw"`
	Description    *string `db:"description"`
	StartYear      *int64  `db:"start_year"`
	StartMonth     *int64  `db:"start_month"`
	IsCurrent      int64   `db:"is_current"`
	EndYear        *int64  `db:"end_year"`
	EndMonth       *int64  `db:"end_month"`
	SkillsUrl      *string `db:"skills_url"`
}

func (q *Queries) InsertExperience(ctx context.Context, arg InsertExperienceParams) error {
	_, err := q.db.ExecContext(ctx, insertExperience,
		arg.PersonID,
		arg.OrganizationID,
		arg.Title,
		arg.LocationRaw,
		arg.Description,
		arg.StartYear,
		arg.StartMonth,
		arg.IsCurrent,
		arg.EndYear,
		arg.EndMonth,
		arg.SkillsUrl,
	)
	return err
}
