// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: init.sql

package model

import (
	"context"
)

const createDatasetDegreesTable = `-- name: CreateDatasetDegreesTable :exec
CREATE TABLE IF NOT EXISTS dataset_degrees (
  id INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE
)
`

func (q *Queries) CreateDatasetDegreesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDatasetDegreesTable)
	return err
}

const createDatasetIndustriesTable = `-- name: CreateDatasetIndustriesTable :exec
CREATE TABLE IF NOT EXISTS dataset_industries (
  id INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE
)
`

func (q *Queries) CreateDatasetIndustriesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDatasetIndustriesTable)
	return err
}

const createDatasetLocationsTable = `-- name: CreateDatasetLocationsTable :exec
CREATE TABLE IF NOT EXISTS dataset_locations (
  id INTEGER PRIMARY KEY,
  city TEXT,
  "state" TEXT,
  country TEXT,
  country_code TEXT,
  UNIQUE (city, "state", country)
)
`

func (q *Queries) CreateDatasetLocationsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDatasetLocationsTable)
	return err
}

const createDatasetSkillsTable = `-- name: CreateDatasetSkillsTable :exec
CREATE TABLE IF NOT EXISTS dataset_skills (
  id INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE
)
`

func (q *Queries) CreateDatasetSkillsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDatasetSkillsTable)
	return err
}

const createDatasetSpecialtiesTable = `-- name: CreateDatasetSpecialtiesTable :exec
CREATE TABLE IF NOT EXISTS dataset_specialies (
  id INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE
)
`

func (q *Queries) CreateDatasetSpecialtiesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDatasetSpecialtiesTable)
	return err
}

const createDatasetStudyFieldsTable = `-- name: CreateDatasetStudyFieldsTable :exec
CREATE TABLE IF NOT EXISTS dataset_study_fields (
  id INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE
)
`

func (q *Queries) CreateDatasetStudyFieldsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDatasetStudyFieldsTable)
	return err
}

const createEducationsTable = `-- name: CreateEducationsTable :exec
CREATE TABLE IF NOT EXISTS educations (
  id INTEGER PRIMARY KEY,
  person_id INTEGER NOT NULL,
  organization_id INTEGER NOT NULL,
  degree_id INTEGER NOT NULL,
  study_field_id INTEGER NOT NULL,
  "description" TEXT,
  start_year INTEGER,
  start_month TEXT,
  end_year INTEGER,
  end_month TEXT,
  FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE CASCADE,
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (degree_id) REFERENCES dataset_degrees(id) ON DELETE SET NULL,
  FOREIGN KEY (study_field_id) REFERENCES dataset_study_fields(id) ON DELETE SET NULL
)
`

func (q *Queries) CreateEducationsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createEducationsTable)
	return err
}

const createExperiencesTable = `-- name: CreateExperiencesTable :exec
CREATE TABLE IF NOT EXISTS experiences (
  id INTEGER PRIMARY KEY,
  person_id INTEGER NOT NULL,
  organization_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  location_id INTEGER,
  "description" TEXT,
  start_year INTEGER,
  start_month TEXT,
  is_current INTEGER NOT NULL,
  end_year INTEGER,
  end_month TEXT,
  skills_url TEXT,
  FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE CASCADE,
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES dataset_locations(id) ON DELETE SET NULL
)
`

func (q *Queries) CreateExperiencesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createExperiencesTable)
	return err
}

const createNetworkConnectionsTable = `-- name: CreateNetworkConnectionsTable :exec
CREATE TABLE IF NOT EXISTS network_connections (
  id INTEGER PRIMARY KEY,
  network_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  UNIQUE (network_id, person_id),
  FOREIGN KEY (network_id) REFERENCES networks(id) ON DELETE CASCADE,
  FOREIGN KEY (person_id) REFERENCES persons(id) ON DELETE CASCADE
)
`

func (q *Queries) CreateNetworkConnectionsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createNetworkConnectionsTable)
	return err
}

const createNetworksTable = `-- name: CreateNetworksTable :exec
CREATE TABLE IF NOT EXISTS networks (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  UNIQUE (user_id, "name"),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
`

func (q *Queries) CreateNetworksTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createNetworksTable)
	return err
}

const createOrganizationIndustriesTable = `-- name: CreateOrganizationIndustriesTable :exec
CREATE TABLE IF NOT EXISTS organization_industries (
  id INTEGER PRIMARY KEY,
  organization_id INTEGER NOT NULL,
  industry_id INTEGER NOT NULL,
  UNIQUE (organization_id, industry_id),
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (industry_id) REFERENCES dataset_industries(id) ON DELETE CASCADE
)
`

func (q *Queries) CreateOrganizationIndustriesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createOrganizationIndustriesTable)
	return err
}

const createOrganizationLocationsTable = `-- name: CreateOrganizationLocationsTable :exec
CREATE TABLE IF NOT EXISTS organization_locations (
  id INTEGER PRIMARY KEY,
  organization_id INTEGER NOT NULL,
  location_id INTEGER NOT NULL,
  is_headquarters INTEGER NOT NULL DEFAULT 0,
  UNIQUE (organization_id, location_id),
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (location_id) REFERENCES dataset_locations(id) ON DELETE CASCADE
)
`

func (q *Queries) CreateOrganizationLocationsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createOrganizationLocationsTable)
	return err
}

const createOrganizationSpecialtiesTable = `-- name: CreateOrganizationSpecialtiesTable :exec
CREATE TABLE IF NOT EXISTS organization_specialties (
  id INTEGER PRIMARY KEY,
  organization_id INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL,
  UNIQUE (organization_id, specialty_id),
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  FOREIGN KEY (specialty_id) REFERENCES dataset_specialties(id) ON DELETE CASCADE
)
`

func (q *Queries) CreateOrganizationSpecialtiesTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createOrganizationSpecialtiesTable)
	return err
}

const createOrganizationsTable = `-- name: CreateOrganizationsTable :exec
CREATE TABLE IF NOT EXISTS organizations (
  id INTEGER PRIMARY KEY,
  "name" TEXT NOT NULL,
  universal_name TEXT NOT NULL,
  website TEXT,
  linkedin_url TEXT NOT NULL,
  logo_url TEXT,
  founded_year INTEGER,
  founded_month TEXT,
  organization_type INTEGER NOT NULL DEFAULT 0,
  employee_count INTEGER,
  student_count INTEGER,
  urn TEXT NOT NULL UNIQUE
)
`

func (q *Queries) CreateOrganizationsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createOrganizationsTable)
	return err
}

const createPersonsTable = `-- name: CreatePersonsTable :exec
CREATE TABLE IF NOT EXISTS persons (
  id INTEGER PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  headline TEXT,
  profile_url TEXT NOT NULL,
  public_identifier TEXT NOT NULL,
  profile_picture_url TEXT,
  about TEXT,
  location_id INTEGER,
  urn TEXT NOT NULL UNIQUE,
  current_company_id INTEGER,
  FOREIGN KEY (location_id) REFERENCES dataset_locations(id) ON DELETE SET NULL,
  FOREIGN KEY (current_company_id) REFERENCES organizations(id) ON DELETE SET NULL
)
`

func (q *Queries) CreatePersonsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createPersonsTable)
	return err
}

const createUsersTable = `-- name: CreateUsersTable :exec
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  username TEXT NOT NULL,
  "password" TEXT NOT NULL,
  apify_token TEXT
)
`

func (q *Queries) CreateUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createUsersTable)
	return err
}
