// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

type DatasetDegrees struct {
	ID   int64  `db:"id"`
	Name string `db:"name"`
}

type DatasetIndustries struct {
	ID   int64  `db:"id"`
	Name string `db:"name"`
}

type DatasetLocations struct {
	ID          int64   `db:"id"`
	City        *string `db:"city"`
	State       *string `db:"state"`
	Country     *string `db:"country"`
	CountryCode *string `db:"country_code"`
}

type DatasetSkills struct {
	ID   int64  `db:"id"`
	Name string `db:"name"`
}

type DatasetSpecialies struct {
	ID   int64  `db:"id"`
	Name string `db:"name"`
}

type DatasetStudyFields struct {
	ID   int64  `db:"id"`
	Name string `db:"name"`
}

type Educations struct {
	ID             int64   `db:"id"`
	PersonID       int64   `db:"person_id"`
	OrganizationID int64   `db:"organization_id"`
	DegreeID       int64   `db:"degree_id"`
	StudyFieldID   int64   `db:"study_field_id"`
	Description    *string `db:"description"`
	StartYear      *int64  `db:"start_year"`
	StartMonth     *string `db:"start_month"`
	EndYear        *int64  `db:"end_year"`
	EndMonth       *string `db:"end_month"`
}

type Experiences struct {
	ID             int64   `db:"id"`
	PersonID       int64   `db:"person_id"`
	OrganizationID int64   `db:"organization_id"`
	Title          string  `db:"title"`
	LocationID     *int64  `db:"location_id"`
	Description    *string `db:"description"`
	StartYear      *int64  `db:"start_year"`
	StartMonth     *string `db:"start_month"`
	IsCurrent      int64   `db:"is_current"`
	EndYear        *int64  `db:"end_year"`
	EndMonth       *string `db:"end_month"`
	SkillsUrl      *string `db:"skills_url"`
}

type NetworkConnections struct {
	ID        int64 `db:"id"`
	NetworkID int64 `db:"network_id"`
	PersonID  int64 `db:"person_id"`
}

type Networks struct {
	ID     int64  `db:"id"`
	UserID int64  `db:"user_id"`
	Name   string `db:"name"`
}

type OrganizationIndustries struct {
	ID             int64 `db:"id"`
	OrganizationID int64 `db:"organization_id"`
	IndustryID     int64 `db:"industry_id"`
}

type OrganizationLocations struct {
	ID             int64 `db:"id"`
	OrganizationID int64 `db:"organization_id"`
	LocationID     int64 `db:"location_id"`
	IsHeadquarters int64 `db:"is_headquarters"`
}

type OrganizationSpecialties struct {
	ID             int64 `db:"id"`
	OrganizationID int64 `db:"organization_id"`
	SpecialtyID    int64 `db:"specialty_id"`
}

type Organizations struct {
	ID               int64   `db:"id"`
	Name             string  `db:"name"`
	UniversalName    string  `db:"universal_name"`
	Website          *string `db:"website"`
	LinkedinUrl      string  `db:"linkedin_url"`
	LogoUrl          *string `db:"logo_url"`
	FoundedYear      *int64  `db:"founded_year"`
	FoundedMonth     *string `db:"founded_month"`
	OrganizationType int64   `db:"organization_type"`
	EmployeeCount    *int64  `db:"employee_count"`
	StudentCount     *int64  `db:"student_count"`
	Urn              string  `db:"urn"`
}

type Persons struct {
	ID                int64   `db:"id"`
	FirstName         string  `db:"first_name"`
	LastName          string  `db:"last_name"`
	Headline          *string `db:"headline"`
	ProfileUrl        string  `db:"profile_url"`
	PublicIdentifier  string  `db:"public_identifier"`
	ProfilePictureUrl *string `db:"profile_picture_url"`
	About             *string `db:"about"`
	LocationID        *int64  `db:"location_id"`
	Urn               string  `db:"urn"`
	CurrentCompanyID  *int64  `db:"current_company_id"`
}

type Users struct {
	ID         int64   `db:"id"`
	Username   string  `db:"username"`
	Password   string  `db:"password"`
	ApifyToken *string `db:"apify_token"`
}
