// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network.sql

package model

import (
	"context"
)

const InsertNetwork = `-- name: InsertNetwork :exec
INSERT INTO networks (user_id, "name") VALUES (?, ?)
`

type InsertNetworkParams struct {
	UserID int64  `db:"user_id"`
	Name   string `db:"name"`
}

func (q *Queries) InsertNetwork(ctx context.Context, arg InsertNetworkParams) error {
	_, err := q.db.ExecContext(ctx, InsertNetwork, arg.UserID, arg.Name)
	return err
}

const InsertNetworkConnection = `-- name: InsertNetworkConnection :exec
INSERT INTO network_connections
(network_id, person_id)
VALUES
(?, ?)
`

type InsertNetworkConnectionParams struct {
	NetworkID int64 `db:"network_id"`
	PersonID  int64 `db:"person_id"`
}

func (q *Queries) InsertNetworkConnection(ctx context.Context, arg InsertNetworkConnectionParams) error {
	_, err := q.db.ExecContext(ctx, InsertNetworkConnection, arg.NetworkID, arg.PersonID)
	return err
}

const SelectNetworkByUserID = `-- name: SelectNetworkByUserID :one
SELECT id, user_id, name, updated_at FROM networks WHERE user_id = ?
`

func (q *Queries) SelectNetworkByUserID(ctx context.Context, userID int64) (Networks, error) {
	row := q.db.QueryRowContext(ctx, SelectNetworkByUserID, userID)
	var i Networks
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const SelectNetworks = `-- name: SelectNetworks :many
SELECT id, user_id, name, updated_at FROM networks WHERE user_id = ? LIMIT ? OFFSET ?
`

type SelectNetworksParams struct {
	UserID int64 `db:"user_id"`
	Limit  int64 `db:"limit"`
	Offset int64 `db:"offset"`
}

func (q *Queries) SelectNetworks(ctx context.Context, arg SelectNetworksParams) ([]Networks, error) {
	rows, err := q.db.QueryContext(ctx, SelectNetworks, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Networks{}
	for rows.Next() {
		var i Networks
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SelectPersonsByNetworkConnections = `-- name: SelectPersonsByNetworkConnections :many
SELECT p.id, p.profile_url
FROM network_connections nc
INNER JOIN persons p ON p.id = nc.person_id
WHERE network_id = ?
`

type SelectPersonsByNetworkConnectionsRow struct {
	ID         int64  `db:"id"`
	ProfileUrl string `db:"profile_url"`
}

func (q *Queries) SelectPersonsByNetworkConnections(ctx context.Context, networkID int64) ([]SelectPersonsByNetworkConnectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, SelectPersonsByNetworkConnections, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectPersonsByNetworkConnectionsRow{}
	for rows.Next() {
		var i SelectPersonsByNetworkConnectionsRow
		if err := rows.Scan(&i.ID, &i.ProfileUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
