// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: network_phase.sql

package model

import (
	"context"
)

const InsertNewConnectionsFromTmp = `-- name: InsertNewConnectionsFromTmp :exec
INSERT INTO connections
(network_id, person_id)
SELECT
  t.network_id,
  t.person_id
FROM tmp_connections t
LEFT JOIN connections c ON c.person_id = t.person_id
  AND c.network_id = ?
WHERE t.person_id IS NOT NULL
  AND c.id IS NULL
`

func (q *Queries) InsertNewConnectionsFromTmp(ctx context.Context, networkID int64) error {
	_, err := q.db.ExecContext(ctx, InsertNewConnectionsFromTmp, networkID)
	return err
}
