// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: person.sql

package model

import (
	"context"
)

const InsertPerson = `-- name: InsertPerson :exec
INSERT INTO persons
(first_name, last_name, headline, profile_url, public_identifier, profile_picture_url, about, location_id, urn, created_at)
VALUES
(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPersonParams struct {
	FirstName         string  `db:"first_name"`
	LastName          string  `db:"last_name"`
	Headline          *string `db:"headline"`
	ProfileUrl        string  `db:"profile_url"`
	PublicIdentifier  string  `db:"public_identifier"`
	ProfilePictureUrl *string `db:"profile_picture_url"`
	About             *string `db:"about"`
	LocationID        *int64  `db:"location_id"`
	Urn               string  `db:"urn"`
	CreatedAt         int64   `db:"created_at"`
}

func (q *Queries) InsertPerson(ctx context.Context, arg InsertPersonParams) error {
	_, err := q.db.ExecContext(ctx, InsertPerson,
		arg.FirstName,
		arg.LastName,
		arg.Headline,
		arg.ProfileUrl,
		arg.PublicIdentifier,
		arg.ProfilePictureUrl,
		arg.About,
		arg.LocationID,
		arg.Urn,
		arg.CreatedAt,
	)
	return err
}
