// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package model

import (
	"context"
)

const CountCompanies = `-- name: CountCompanies :one
SELECT COUNT(*) FROM organizations WHERE organization_type = 0
`

func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountPersons = `-- name: CountPersons :one
SELECT COUNT(*) FROM persons
`

func (q *Queries) CountPersons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountPersons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountSchools = `-- name: CountSchools :one
SELECT COUNT(*) FROM organizations WHERE organization_type = 1
`

func (q *Queries) CountSchools(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSchools)
	var count int64
	err := row.Scan(&count)
	return count, err
}
